services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./backend/uploads:/var/www/uploads:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_modules:
  frontend_modules: